site_name: SmartTask Documentation
site_description: Official documentation for SmartTask – a smart way to manage tasks and teams.
site_author: Dinesh Singh
theme:
  name: material
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Features:
    - Feature 1: features/feature1.md
    - Feature 2: features/feature2.md
  - FAQ: faq.md
  - Release Notes: release-notes.md
